#!/usr/bin/env python3
"""Generate /courses.html, the course catalog.

One page listing every course, chapter and lesson, laid out the way the in-app table of
contents is. Everything is read from the source of truth rather than typed by hand:

  lessons/<course>/toc.json        the full planned syllabus, chapters and lesson titles
  lessons/<course>/chapter-*.json  which of those lessons are actually written
  lessons/<course>/slugmap.json    the SEO page slug for each written lesson

A lesson is only linked when it is BOTH written and present in the slugmap, because the
slugmap is regenerated by gen_seo_pages.py and can lag behind a freshly shipped lesson.
Linking on "written" alone would emit 404s for exactly the newest lesson each time.

Usage:  python3 tools/gen_catalog.py        then commit courses.html
"""
import json, os, glob, html as H

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BASE = "https://quanticaedu.com"
COURSES = [
    ("prealgebra", "Prealgebra",
     "Arithmetic, exponents, fractions, ratios and geometry."),
    ("algebra1", "Algebra I",
     "Expressions through quadratics, functions and logarithms. Fifteen chapters, written in order."),
]


def load(course):
    toc = json.load(open(f"{ROOT}/lessons/{course}/toc.json", encoding="utf-8"))
    live = {}
    for f in glob.glob(f"{ROOT}/lessons/{course}/chapter-*.json"):
        live.update(json.load(open(f, encoding="utf-8")))
    slugs = {}
    p = f"{ROOT}/lessons/{course}/slugmap.json"
    if os.path.exists(p):
        slugs = json.load(open(p, encoding="utf-8"))
    return toc, live, slugs


def course_section(slug, title, blurb):
    toc, live, slugs = load(slug)
    n_ch = len(toc)
    n_live = sum(1 for ch in toc for l in ch["lessons"] if l["k"] in live)
    n_all = sum(len(ch["lessons"]) for ch in toc)
    complete = n_live == n_all

    cards = []
    for ch in toc:
        # Only WRITTEN lessons are listed. An unwritten lesson used to render as a greyed
        # "soon" row, and 38 of those across the page made a real course read like a
        # roadmap. The chapter title still appears so the shape of the course is visible;
        # what is hidden is the lesson-by-lesson evidence of what is missing.
        items = []
        for l in ch["lessons"]:
            k, t = l["k"], H.escape(l["t"])
            if k in live and k in slugs:
                items.append(f'<li><span class="k">{k}</span>'
                             f'<a href="/{slug}/{slugs[k]}">{t}</a></li>')
            elif k in live:
                # written but no SEO page yet; still show it as available, just unlinked
                items.append(f'<li><span class="k">{k}</span><span class="t">{t}</span></li>')
        ch_live = sum(1 for l in ch["lessons"] if l["k"] in live)
        n_ch_lessons = len(ch["lessons"])
        state = "done" if ch_live == n_ch_lessons else ("part" if ch_live else "none")
        if ch_live == 0:
            count = "In writing"
            body = ""
        elif ch_live == n_ch_lessons:
            count = f"{ch_live} lesson" + ("s" if ch_live != 1 else "")
            body = f'<ol>{"".join(items)}</ol>'
        else:
            count = f"{ch_live} of {n_ch_lessons} lessons ready"
            body = f'<ol>{"".join(items)}</ol>'
        cards.append(
            f'<article class="ch {state}">'
            f'<header><span class="chn">Chapter {ch["n"]}</span>'
            f'<h3>{H.escape(ch["t"])}</h3>'
            f'<span class="chc">{count}</span></header>'
            f'{body}</article>')

    badge = ('<span class="badge done">Complete</span>' if complete
             else '<span class="badge wip">In progress</span>')
    return (f'<section class="course" id="{slug}">'
            f'<div class="chead"><div>'
            f'<h2>{H.escape(title)}</h2>'
            f'<p class="cblurb">{H.escape(blurb)}</p></div>'
            f'<div class="cmeta">{badge}'
            f'<span class="cstat">{n_live} lessons ready</span>'
            f'<a class="btn btn-primary" href="/landing?course={slug}&amp;start=1">Start {H.escape(title)}</a>'
            f'</div></div>'
            f'<div class="grid">{"".join(cards)}</div></section>'), n_live, n_all


def main():
    sections, tot_live, tot_all = [], 0, 0
    for slug, title, blurb in COURSES:
        sec, a, b = course_section(slug, title, blurb)
        sections.append(sec); tot_live += a; tot_all += b

    ld = json.dumps({
        "@context": "https://schema.org", "@type": "ItemList",
        "name": "Quantica course catalog",
        "itemListElement": [
            {"@type": "ListItem", "position": i + 1, "name": t,
             "url": f"{BASE}/{s}"} for i, (s, t, _) in enumerate(COURSES)]
    }, separators=(",", ":"))

    page = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Course Catalog | Quantica</title>
<meta name="description" content="Every Quantica course, chapter by chapter. {tot_live} lessons written across prealgebra and algebra, each one taught by solving problems with a tutor on every problem.">
<link rel="canonical" href="{BASE}/courses">
<link rel="icon" href="/favicon.svg">
<meta property="og:type" content="website">
<meta property="og:title" content="Course Catalog | Quantica">
<meta property="og:description" content="Every course, chapter by chapter. {tot_live} lessons written across prealgebra and algebra.">
<meta property="og:url" content="{BASE}/courses">
<meta property="og:image" content="{BASE}/og-default.png">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:image" content="{BASE}/og-default.png">
<script type="application/ld+json">{ld}</script>
<link rel="preconnect" href="https://api.fontshare.com">
<link rel="preconnect" href="https://cdn.fontshare.com" crossorigin>
<link href="https://api.fontshare.com/v2/css?f%5B%5D=chillax@300,400,500,600,700&display=swap" rel="stylesheet">
<script>
  window.dataLayer=window.dataLayer||[];
  function gtag(){{dataLayer.push(arguments);}}
  window.track=function(n,p){{ try{{ gtag('event',n,p||{{}}); }}catch(e){{}} }};
  (function(){{try{{var h=location.hostname;if(h!=='quanticaedu.com'&&h!=='www.quanticaedu.com')return;if(localStorage.getItem('qa_internal')==='1')return;var s=document.createElement('script');s.async=true;s.src='https://www.googletagmanager.com/gtag/js?id=G-98WQ2BFR6N';document.head.appendChild(s);gtag('js',new Date());gtag('config','G-98WQ2BFR6N',{{allow_google_signals:false,allow_ad_personalization_signals:false}});}}catch(e){{}}}})();
</script>
<style>
  :root{{--paper:#FCFEFB;--ink:#16281B;--gray:#5c5c58;--line:#e3ece1;--card:#fff;
        --lime:#D6F5A3;--lime-deep:#8FCB4A;--forest:#2E7D32;--tint:#F1FAE4;--max:1180px}}
  *{{box-sizing:border-box}}
  body{{margin:0;background:var(--paper);color:var(--ink);
       font-family:'Chillax',system-ui,sans-serif;font-weight:400;line-height:1.65;-webkit-font-smoothing:antialiased}}
  a{{color:inherit;text-decoration:none}}
  h1,h2,h3{{font-family:'Chillax',system-ui,sans-serif;letter-spacing:-.03em;line-height:1.02;margin:0}}
  .wrap{{max-width:var(--max);margin:0 auto;padding:0 24px}}

  .nav{{border-bottom:1px solid var(--line);background:rgba(252,254,251,.92);
       position:sticky;top:0;z-index:20;backdrop-filter:blur(8px)}}
  .nav-in{{display:flex;align-items:center;justify-content:space-between;height:74px}}
  .brand{{display:flex;align-items:center;gap:.55em;font-family:'Chillax',sans-serif;
         font-weight:700;font-size:1.42rem;letter-spacing:-.03em}}
  .brand img{{width:32px;height:32px}}
  .nav-links{{display:flex;align-items:center;gap:2rem}}
  .nav-links a{{font-size:.95rem;color:var(--gray);font-weight:500;letter-spacing:0}}
  .nav-links a:hover,.nav-links a.on{{color:var(--forest)}}
  .btn{{display:inline-flex;align-items:center;font-weight:700;font-size:.95rem;
       padding:.75em 1.5em;border-radius:0;border:1.5px solid transparent;white-space:nowrap}}
  .btn-primary{{background:var(--lime);color:var(--ink)}}
  .btn-primary:hover{{background:var(--lime-deep)}}

  .hero{{padding:64px 0 30px}}
  .hero h1{{font-size:clamp(2.5rem,6vw,4rem);font-weight:700}}
  .hero p{{font-size:1.15rem;font-weight:300;color:var(--gray);max-width:56ch;margin:16px 0 0}}

  .course{{padding:38px 0 10px;border-top:1px solid var(--line);margin-top:34px}}
  .chead{{display:flex;flex-wrap:wrap;gap:22px;align-items:flex-start;
         justify-content:space-between;margin-bottom:26px}}
  .chead h2{{font-size:2.1rem;font-weight:700}}
  .cblurb{{color:var(--gray);font-weight:300;margin:8px 0 0;max-width:52ch}}
  .cmeta{{display:flex;flex-direction:column;align-items:flex-end;gap:9px}}
  .badge{{font-size:.78rem;font-weight:700;border-radius:0;padding:5px 12px;
         text-transform:uppercase;letter-spacing:.05em}}
  .badge.done{{background:var(--tint);color:var(--forest);border:1px solid #cfe8bf}}
  .badge.wip{{background:#FFF6E0;color:#8a5a08;border:1px solid #f1dfae}}
  .cstat{{font-size:.86rem;color:var(--gray)}}

  .grid{{display:grid;grid-template-columns:repeat(auto-fill,minmax(320px,1fr));gap:18px}}
  .ch{{background:var(--card);border:1px solid var(--line);border-radius:0;padding:20px 22px 16px}}
  .ch.none{{background:#fbfdfa;border-style:dashed}}
  .ch header{{margin-bottom:12px}}
  .chn{{font-size:.72rem;font-weight:700;letter-spacing:.09em;text-transform:uppercase;color:var(--forest)}}
  .ch.none .chn{{color:var(--gray)}}
  .ch h3{{font-size:1.16rem;font-weight:600;margin:5px 0 4px}}
  .chc{{font-size:.8rem;color:var(--gray)}}
  .ch ol{{list-style:none;margin:0;padding:0}}
  .ch li{{display:flex;gap:9px;align-items:baseline;padding:5px 0;font-size:.94rem;
         border-top:1px solid #f2f6f0}}
  .ch li:first-child{{border-top:0}}
  .ch li .k{{font-size:.76rem;font-weight:700;color:var(--forest);min-width:2.1em;flex:none}}
  .ch li a:hover{{color:var(--forest);text-decoration:underline}}
  .ch li.soon{{color:#93a08f}}
  .ch li.soon .k{{color:#b6c2b0}}
  .ch li em{{margin-left:auto;font-style:normal;font-size:.7rem;text-transform:uppercase;
            letter-spacing:.06em;color:#b6c2b0;flex:none}}

  .foot{{border-top:1px solid var(--line);margin-top:56px;padding:30px 0 46px;
        font-size:.9rem;color:var(--gray)}}
  .foot a{{margin-right:18px}}
  .foot a:hover{{color:var(--forest)}}
  @media(max-width:720px){{.nav-links{{display:none}}.cmeta{{align-items:flex-start}}}}
</style>
</head>
<body>
<header class="nav"><div class="wrap nav-in">
  <a class="brand" href="/"><img src="/favicon.svg" alt="" width="32" height="32" aria-hidden="true">Quantica</a>
  <nav class="nav-links" aria-label="Primary">
    <a href="/#tutor">The tutor</a>
    <a href="/courses" class="on">Courses</a>
    <a href="/blog">Blog</a>
    <a href="/#pricing">Pricing</a>
  </nav>
  <a class="btn btn-primary" href="/landing?start=1">Start free</a>
</div></header>

<main class="wrap">
  <section class="hero">
    <h1>Course catalog</h1>
    <p>All courses at Quantica are listed below, along with their contents and lessons.
       {tot_live} lessons are written and open now!</p>
  </section>
  {"".join(sections)}
</main>

<footer class="foot"><div class="wrap">
  <a href="/">Home</a><a href="/prealgebra">Prealgebra</a><a href="/algebra1">Algebra I</a>
  <a href="/blog">Blog</a><a href="/terms">Terms</a><a href="/privacy">Privacy</a>
</div></footer>
</body>
</html>
"""
    out = f"{ROOT}/courses.html"
    open(out, "w", encoding="utf-8").write(page)
    print(f"wrote {out}  ({tot_live} of {tot_all} lessons across {len(COURSES)} courses, {len(page)} bytes)")


if __name__ == "__main__":
    main()
