#!/usr/bin/env python3
"""Stamp the canonical analytics block into the hand-written pages.

    python3 tools/stamp_analytics.py          # write
    python3 tools/stamp_analytics.py --check  # exit 1 if any page is stale

Why a tool rather than five hand edits. The block carries the founder opt-out, the Global
Privacy Control gate and the Europe exclusion, and privacy.html sections 6 and 7 describe
all three as things the site does. Five hand-maintained copies drift, and when one drifts
the legal page becomes false on that page only, which nobody would ever notice.

The block is inserted between markers and is idempotent, so re-running replaces rather than
duplicates. Everything outside the markers is left alone.

WHAT THIS DELIBERATELY DOES NOT DO. It never touches a page's existing GA4 snippet. Those
snippets differ slightly between pages and replacing them risks configuring GA4 twice, which
would double every page view. GA4 is only added where it is missing entirely.

SCOPE, which mirrors privacy.html section 7 exactly. Change one and you must change the
other, or the policy is false.
  marketing -> GA4, Meta pixel, Clarity
  app       -> GA4, Meta pixel. NEVER Clarity, because the policy promises no session
               recorder runs where lessons are worked.
  basic     -> GA4 only. For legal and error pages, which need to be visible in reporting
               but have nothing to advertise against.
The 113 generated lesson pages are not in this list on purpose. They are stamped by
tools/gen_seo_pages.py with GA4 only, because an unaccompanied child is most likely to
arrive there from a search.
"""

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

PIXEL_ID = "1061468839592852"
GA_ID = "G-98WQ2BFR6N"

# path -> mode
#
# prealgebra.html and algebra1.html are NOT here on purpose. tools/gen_seo_pages.py regenerates
# those two hub pages from a template, so stamping them worked right up until the next
# regeneration silently wiped the pixel, Clarity, click tracking and attribution back out. The
# generator imports block() from this module instead, so there is still exactly one definition.
TARGETS = {
    "courses.html": "marketing",
    "blog.html": "marketing",
    "blog/how-to-solve-one-step-equations.html": "marketing",
    "blog/watching-your-child-struggle-with-math.html": "marketing",
    "blog/why-cant-you-divide-by-zero.html": "marketing",
    "blog/why-is-a-negative-times-a-negative-positive.html": "marketing",
    "blog/why-students-memorize-math.html": "marketing",
    # The course roadmap. Signed-in surface, so no Clarity. It is not the lesson workspace,
    # but it is close enough that recording it would strain the wording in section 7.
    "paths/home.html": "app",
    "privacy.html": "basic",
    "terms.html": "basic",
    "404.html": "basic",
}

START = "<!-- QA-ANALYTICS v1 START (generated by tools/stamp_analytics.py, do not hand-edit) -->"
END = "<!-- QA-ANALYTICS v1 END -->"


def ga_snippet():
    return f"""<script>
  window.dataLayer=window.dataLayer||[];
  function gtag(){{dataLayer.push(arguments);}}
  (function(){{try{{
    var h=location.hostname; if(h!=='quanticaedu.com'&&h!=='www.quanticaedu.com') return;
    if(location.search.indexOf('imfounder=1')>-1&&!localStorage.getItem('qa_internal')){{
      localStorage.setItem('qa_internal','1'); alert('Got it. Analytics is now off on this device.');
    }}
    if(localStorage.getItem('qa_internal')==='1') return;
    var s=document.createElement('script'); s.async=true;
    s.src='https://www.googletagmanager.com/gtag/js?id={GA_ID}';
    document.head.appendChild(s);
    gtag('js',new Date());
    gtag('config','{GA_ID}',{{allow_google_signals:false,allow_ad_personalization_signals:false}});
  }}catch(e){{}}}})();
</script>"""


def ads_section(mode):
    """The pixel and Clarity. Returns empty for basic pages, which get GA4 only.

    privacy.html and terms.html are basic on purpose. Section 7 scopes the pixel to
    marketing pages and the course app, and a legal page is neither. Loading an
    advertising pixel on the page that explains your advertising pixel is also the kind
    of detail a regulator or a journalist notices first.
    """
    if mode == "basic":
        return """
  // No advertising tools on this page, by design. privacy.html section 7 scopes the Meta
  // pixel to marketing pages and the course app, and a legal or error page is neither.
  // GA4 alone, so the page is still visible in reporting."""

    clarity_decl = "\n  window.CLARITY_ID='';   // paste from clarity.microsoft.com, AFTER setting masking to Strict" if mode == "marketing" else ""
    clarity_load = """
    var cid=window.CLARITY_ID;
    if(cid){
      (function(c,l,a,r,i,t,y){c[a]=c[a]||function(){(c[a].q=c[a].q||[]).push(arguments)};
      t=l.createElement(r);t.async=1;t.src="https://www.clarity.ms/tag/"+i;
      y=l.getElementsByTagName(r)[0];y.parentNode.insertBefore(t,y);})(window,document,'clarity','script',cid);
    }""" if mode == "marketing" else """
    // No Clarity here. privacy.html section 7 promises no session recorder runs where
    // lessons are worked, and this is a signed-in course surface."""

    return f"""
  window.META_PIXEL_ID='{PIXEL_ID}';{clarity_decl}
  window.fbTrack=function(n,p){{ try{{ if(window.fbq) fbq('track',n,p||{{}}); }}catch(e){{}} }};
  window.fbTrackCustom=function(n,p){{ try{{ if(window.fbq) fbq('trackCustom',n,p||{{}}); }}catch(e){{}} }};

  // One gate for every advertising tool. privacy.html section 6 names Global Privacy Control
  // as the opt-out, so this is a promise rather than an optimisation.
  window.__qaAdsAllowed=function(){{
    try{{
      var h=location.hostname;
      if(h!=='quanticaedu.com'&&h!=='www.quanticaedu.com') return false;
      if(localStorage.getItem('qa_internal')==='1') return false;
      if(navigator.globalPrivacyControl===true) return false;
      var tz=''; try{{ tz=Intl.DateTimeFormat().resolvedOptions().timeZone||''; }}catch(e){{}}
      if(tz.indexOf('Europe/')===0) return false;   // no consent banner, so ePrivacy and PECR are not met
      return true;
    }}catch(e){{ return false; }}
  }};

  (function(){{try{{
    if(!window.__qaAdsAllowed()) return;
    var id=window.META_PIXEL_ID;
    if(id){{
      !function(f,b,e,v,n,t,s){{if(f.fbq)return;n=f.fbq=function(){{n.callMethod?n.callMethod.apply(n,arguments):n.queue.push(arguments)}};
      if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';n.queue=[];t=b.createElement(e);t.async=!0;
      t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}}(window,document,'script',
      'https://connect.facebook.net/en_US/fbevents.js');
      fbq('dataProcessingOptions',['LDU'],0,0);   // must precede init
      fbq('set','autoConfig',false,id);           // stops Meta harvesting button text and form fields
      fbq('init',id);
      fbq('track','PageView');
    }}{clarity_load}
  }}catch(e){{}}}})();
"""


ATTR = """
  /* First-touch attribution, captured on every page because an ad or a search result can land
     anywhere. Written to localStorage and NEVER forwarded onto internal links. Appending utm
     parameters to same-origin hrefs is the obvious-looking approach and it is wrong: GA4 starts
     a NEW session whenever campaign parameters appear on a navigation, so every internal click
     would become a fresh campaign-tagged session, inflating session counts and making per-page
     conversion rate uncountable. It is unnecessary too, since / and /landing share an origin and
     therefore share this storage.

     Only written when there is an actual signal. A direct visit deliberately leaves the key
     unset so that a later tagged visit still gets recorded, which loses strict first-touch
     purity and keeps the thing that matters, which is never losing the ad click. */
  (function(){ try{
    var K='quantica.attr.v1';
    if(localStorage.getItem(K)) return;                       // first touch wins
    var p=new URLSearchParams(location.search), a={}, any=false;
    ['utm_source','utm_medium','utm_campaign','utm_term','utm_content','fbclid','gclid'].forEach(function(k){
      var v=p.get(k); if(v){ a[k]=String(v).slice(0,120); any=true; }
    });
    var ref=''; try{ ref=document.referrer?new URL(document.referrer).hostname:''; }catch(e){}
    if(ref && ref!==location.hostname){ a.referrer=ref; any=true; }
    if(!any) return;
    a.landing=location.pathname.slice(0,120);
    a.at=new Date().toISOString().slice(0,10);
    localStorage.setItem(K,JSON.stringify(a));
  }catch(e){} })();
"""


def block(mode, needs_ga):
    parts = [START]
    if needs_ga:
        parts.append(ga_snippet())
    parts.append(f"""<script>
  window.track=window.track||function(n,p){{ try{{ gtag('event',n,p||{{}}); }}catch(e){{}} }};
{ATTR}{ads_section(mode)}
  // Click tracking, delegated from the document so it covers every link including any added
  // later. The label comes from data-cta when present and otherwise from the href. NEVER
  // from textContent, because on the marketing page that text is overwritten with the signed
  // in user's name or the local-part of their email.
  document.addEventListener('click',function(ev){{
    try{{
      var a=ev.target && ev.target.closest ? ev.target.closest('a[href]') : null;
      if(!a) return;
      var href=a.getAttribute('href')||'';
      var dest='page';
      if(href.indexOf('/landing')===0){{
        // A lesson or problem-set deep link is a content click, not free-signup intent. The
        // hub pages link every lesson as /landing?course=X&lesson=Y, so without this branch
        // each one would fire StartFreeClick and inflate the exact signal a campaign would
        // be optimised on.
        dest = href.indexOf('upgrade=yearly')>-1 ? 'upgrade_yearly'
             : href.indexOf('upgrade=monthly')>-1 ? 'upgrade_monthly'
             : href.indexOf('signin')>-1 ? 'signin'
             : (href.indexOf('lesson=')>-1||href.indexOf('pset=')>-1||href.indexOf('practice=')>-1) ? 'lesson'
             : 'start';
      }}
      else if(href.charAt(0)==='#') dest='anchor';
      else if(href.indexOf('mailto:')===0) dest='email';
      else if(!/^\\//.test(href)) dest='external';
      track('cta_click',{{cta:a.getAttribute('data-cta')||href.slice(0,60),cta_dest:dest,transport_type:'beacon'}});
      if(dest==='start' && window.fbTrackCustom) fbTrackCustom('StartFreeClick',{{cta:a.getAttribute('data-cta')||href.slice(0,60)}});   // no-op where fbTrackCustom is undefined, ie basic pages
    }}catch(e){{}}
  }},true);

  // Scroll depth. document.scrollingElement, not documentElement, because paths/home.html has
  // no DOCTYPE and therefore renders in quirks mode, where scrolling lives on document.body
  // and a documentElement reading is always zero.
  (function(){{
    var marks=[25,50,75,100], hit={{}};
    window.addEventListener('scroll',function(){{
      try{{
        var d=document.scrollingElement||document.documentElement;
        var h=d.scrollHeight-d.clientHeight; if(h<=0) return;
        var pct=Math.round(d.scrollTop/h*100);
        marks.forEach(function(m){{ if(pct>=m && !hit[m]){{ hit[m]=1; track('scroll_depth',{{percent:m,transport_type:'beacon'}}); }} }});
      }}catch(e){{}}
    }},{{passive:true}});
  }})();
</script>""")
    parts.append(END)
    return "\n".join(parts)


def stamp(path, mode, check=False):
    p = ROOT / path
    if not p.exists():
        return ("MISSING", path)
    src = p.read_text()

    # Decide GA4 by looking at the page WITHOUT any previously stamped block. Checking only
    # the text before the marker was wrong: the block is inserted high in the head, above a
    # page's own GA4 snippet further down, so on the second run the check saw no GA4 above it
    # and added a second copy. Two gtag('config') calls means every page view counted twice,
    # which is the kind of error that quietly doubles a number nobody re-derives.
    without_block = re.sub(re.escape(START) + r".*?" + re.escape(END), "", src, flags=re.S)
    needs_ga = "googletagmanager" not in without_block

    new_block = block(mode, needs_ga)

    if START in src and END in src:
        out = re.sub(re.escape(START) + r".*?" + re.escape(END), lambda m: new_block, src, flags=re.S)
    else:
        # Insert as early as possible. These pages vary, some have no <head> tag at all, so
        # anchor on the first element that is definitely inside the head.
        for anchor in ('<meta name="viewport"', "<meta charset", "<head>"):
            i = src.find(anchor)
            if i >= 0:
                j = src.index(">", i) + 1
                out = src[:j] + "\n" + new_block + src[j:]
                break
        else:
            return ("NO-ANCHOR", path)

    if out == src:
        return ("unchanged", path)
    if check:
        return ("STALE", path)
    p.write_text(out)
    return ("stamped", path)


if __name__ == "__main__":
    check = "--check" in sys.argv
    results = [stamp(path, mode, check) for path, mode in TARGETS.items()]
    for status, path in results:
        print(f"  {status:<10} {path}")
    bad = [r for r in results if r[0] in ("STALE", "MISSING", "NO-ANCHOR")]
    if bad:
        print(f"\n{len(bad)} page(s) need attention")
        sys.exit(1)
    print(f"\n{len(results)} pages OK")
